/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    sliders: Slider;
    trending: Trending;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    sliders: SlidersSelect<false> | SlidersSelect<true>;
    trending: TrendingSelect<false> | TrendingSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    footer: Footer;
    'ads-config': AdsConfig;
    header: Header;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'ads-config': AdsConfigSelect<false> | AdsConfigSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sliders".
 */
export interface Slider {
  id: number;
  title: string;
  category: string;
  /**
   * Link when click on
   */
  slug: string;
  image: number | Media;
  /**
   * Ascending
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trending".
 */
export interface Trending {
  id: number;
  keyword: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  category: number | Category;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  isFeatured?: boolean | null;
  isTrending?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    relatedPosts?: (number | Post)[] | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'sliders';
        value: number | Slider;
      } | null)
    | ({
        relationTo: 'trending';
        value: number | Trending;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sliders_select".
 */
export interface SlidersSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  slug?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trending_select".
 */
export interface TrendingSelect<T extends boolean = true> {
  keyword?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  status?: T;
  publishedAt?: T;
  isFeatured?: T;
  isTrending?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        relatedPosts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  trending_in_top?:
    | {
        keyword: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  utamaSection?: {
    title?: string | null;
    featuredMain?: (number | null) | Post;
    featuredSide?: (number | Post)[] | null;
    featuredBullet?: (number | Post)[] | null;
    gridPosts?: (number | Post)[] | null;
    terkiniLimit?: number | null;
    trendingLimit?: number | null;
  };
  disyorkanSection?: {
    title?: string | null;
    mainPost?: (number | null) | Post;
    subPosts?: (number | Post)[] | null;
  };
  rencanaSection?: {
    title?: string | null;
    featuredPosts?: (number | Post)[] | null;
    sidePosts?: (number | Post)[] | null;
  };
  sukanSection?: {
    title?: string | null;
    featuredPosts?: (number | Post)[] | null;
    sidePosts?: (number | Post)[] | null;
  };
  duniaSection?: {
    title?: string | null;
    featuredPosts?: (number | Post)[] | null;
    sidePosts?: (number | Post)[] | null;
  };
  bisnesSection?: {
    title?: string | null;
    featuredPosts?: (number | Post)[] | null;
    subPosts?: (number | Post)[] | null;
  };
  hiburanSection?: {
    title?: string | null;
    featuredPosts?: (number | Post)[] | null;
    subPosts?: (number | Post)[] | null;
  };
  gayaHidupSection?: {
    title?: string | null;
    featuredPost?: (number | null) | Post;
    subPosts?: (number | Post)[] | null;
  };
  bhPlusSection?: {
    title?: string | null;
    featuredPosts?: (number | Post)[] | null;
    infografikSection?: {
      title?: string | null;
      featuredImage?: (number | null) | Media;
      linkUrl?: string | null;
    };
    galeriFotoSection?: {
      title?: string | null;
      galleryImages?:
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    subPosts?: (number | Post)[] | null;
  };
  infografikSection?: {
    title?: string | null;
    featuredImage?: (number | null) | Media;
    linkUrl?: string | null;
  };
  galeriFotoSection?: {
    title?: string | null;
    galleryImages?:
      | {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  podcastSection?: {
    title?: string | null;
    channelLogo?: (number | null) | Media;
    videos?: (number | Post)[] | null;
  };
  bhTvSection?: {
    title?: string | null;
    channelLogo?: (number | null) | Media;
    mainVideo?: (number | null) | Post;
    subVideos?: (number | Post)[] | null;
  };
  videoTerkiniSection?: {
    title?: string | null;
    channelLogo?: (number | null) | Media;
    videos?: (number | Post)[] | null;
  };
  sihatSection: {
    title: string;
    moreText?: string | null;
    moreLink?: string | null;
    /**
     * Chọn 1 bài viết chính hiển thị ảnh lớn ở trên cùng
     */
    featuredPost?: (number | null) | Post;
    /**
     * Chọn danh sách các bài viết nhỏ hiển thị bên dưới (thường là 4 bài)
     */
    subPosts?: (number | Post)[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo: number | Media;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'whatsapp' | 'youtube' | 'tiktok' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  appStoreLinks?: {
    appStoreUrl?: string | null;
    googlePlayUrl?: string | null;
  };
  columns?:
    | {
        title?: string | null;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  bottomLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads-config".
 */
export interface AdsConfig {
  id: number;
  BH_Web_Billboard_Homepage_970x250?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
    sizePreset?:
      | (
          | 'max-w-[970px] aspect-[970/90]'
          | 'max-w-[300px] aspect-[300/250]'
          | 'max-w-[320px] aspect-[320/50]'
          | 'max-w-[320px] aspect-[320/100]'
          | 'custom'
        )
      | null;
    customWidth?: number | null;
    customHeight?: number | null;
  };
  BH_300x250?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
    sizePreset?:
      | (
          | 'max-w-[970px] aspect-[970/90]'
          | 'max-w-[300px] aspect-[300/250]'
          | 'max-w-[320px] aspect-[320/50]'
          | 'max-w-[320px] aspect-[320/100]'
          | 'custom'
        )
      | null;
    customWidth?: number | null;
    customHeight?: number | null;
  };
  BH_300x250_b?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
    sizePreset?:
      | (
          | 'max-w-[970px] aspect-[970/90]'
          | 'max-w-[300px] aspect-[300/250]'
          | 'max-w-[320px] aspect-[320/50]'
          | 'max-w-[320px] aspect-[320/100]'
          | 'custom'
        )
      | null;
    customWidth?: number | null;
    customHeight?: number | null;
  };
  BH_320x50?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
    sizePreset?:
      | (
          | 'max-w-[970px] aspect-[970/90]'
          | 'max-w-[300px] aspect-[300/250]'
          | 'max-w-[320px] aspect-[320/50]'
          | 'max-w-[320px] aspect-[320/100]'
          | 'custom'
        )
      | null;
    customWidth?: number | null;
    customHeight?: number | null;
  };
  BH_HP_Sticky_Leaderboard?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
  };
  BH_Mobile_Banner?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
    sizePreset?:
      | (
          | 'max-w-[970px] aspect-[970/90]'
          | 'max-w-[300px] aspect-[300/250]'
          | 'max-w-[320px] aspect-[320/50]'
          | 'max-w-[320px] aspect-[320/100]'
          | 'custom'
        )
      | null;
    customWidth?: number | null;
    customHeight?: number | null;
  };
  BH_Mobile_Banner_b?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
    sizePreset?:
      | (
          | 'max-w-[970px] aspect-[970/90]'
          | 'max-w-[300px] aspect-[300/250]'
          | 'max-w-[320px] aspect-[320/50]'
          | 'max-w-[320px] aspect-[320/100]'
          | 'custom'
        )
      | null;
    customWidth?: number | null;
    customHeight?: number | null;
  };
  BH_Multisize_HouseAds?: {
    active?: boolean | null;
    imageUrl?: string | null;
    link?: string | null;
    code?: string | null;
    sizePreset?:
      | (
          | 'max-w-[970px] aspect-[970/90]'
          | 'max-w-[300px] aspect-[300/250]'
          | 'max-w-[320px] aspect-[320/50]'
          | 'max-w-[320px] aspect-[320/100]'
          | 'custom'
        )
      | null;
    customWidth?: number | null;
    customHeight?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  sliders?:
    | {
        title: string;
        category: string;
        /**
         * Link when click on
         */
        slug: string;
        image: number | Media;
        /**
         * Ascending
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  trending_in_top?:
    | T
    | {
        keyword?: T;
        order?: T;
        id?: T;
      };
  utamaSection?:
    | T
    | {
        title?: T;
        featuredMain?: T;
        featuredSide?: T;
        featuredBullet?: T;
        gridPosts?: T;
        terkiniLimit?: T;
        trendingLimit?: T;
      };
  disyorkanSection?:
    | T
    | {
        title?: T;
        mainPost?: T;
        subPosts?: T;
      };
  rencanaSection?:
    | T
    | {
        title?: T;
        featuredPosts?: T;
        sidePosts?: T;
      };
  sukanSection?:
    | T
    | {
        title?: T;
        featuredPosts?: T;
        sidePosts?: T;
      };
  duniaSection?:
    | T
    | {
        title?: T;
        featuredPosts?: T;
        sidePosts?: T;
      };
  bisnesSection?:
    | T
    | {
        title?: T;
        featuredPosts?: T;
        subPosts?: T;
      };
  hiburanSection?:
    | T
    | {
        title?: T;
        featuredPosts?: T;
        subPosts?: T;
      };
  gayaHidupSection?:
    | T
    | {
        title?: T;
        featuredPost?: T;
        subPosts?: T;
      };
  bhPlusSection?:
    | T
    | {
        title?: T;
        featuredPosts?: T;
        infografikSection?:
          | T
          | {
              title?: T;
              featuredImage?: T;
              linkUrl?: T;
            };
        galeriFotoSection?:
          | T
          | {
              title?: T;
              galleryImages?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
            };
        subPosts?: T;
      };
  infografikSection?:
    | T
    | {
        title?: T;
        featuredImage?: T;
        linkUrl?: T;
      };
  galeriFotoSection?:
    | T
    | {
        title?: T;
        galleryImages?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
      };
  podcastSection?:
    | T
    | {
        title?: T;
        channelLogo?: T;
        videos?: T;
      };
  bhTvSection?:
    | T
    | {
        title?: T;
        channelLogo?: T;
        mainVideo?: T;
        subVideos?: T;
      };
  videoTerkiniSection?:
    | T
    | {
        title?: T;
        channelLogo?: T;
        videos?: T;
      };
  sihatSection?:
    | T
    | {
        title?: T;
        moreText?: T;
        moreLink?: T;
        featuredPost?: T;
        subPosts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  appStoreLinks?:
    | T
    | {
        appStoreUrl?: T;
        googlePlayUrl?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads-config_select".
 */
export interface AdsConfigSelect<T extends boolean = true> {
  BH_Web_Billboard_Homepage_970x250?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
        sizePreset?: T;
        customWidth?: T;
        customHeight?: T;
      };
  BH_300x250?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
        sizePreset?: T;
        customWidth?: T;
        customHeight?: T;
      };
  BH_300x250_b?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
        sizePreset?: T;
        customWidth?: T;
        customHeight?: T;
      };
  BH_320x50?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
        sizePreset?: T;
        customWidth?: T;
        customHeight?: T;
      };
  BH_HP_Sticky_Leaderboard?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
      };
  BH_Mobile_Banner?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
        sizePreset?: T;
        customWidth?: T;
        customHeight?: T;
      };
  BH_Mobile_Banner_b?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
        sizePreset?: T;
        customWidth?: T;
        customHeight?: T;
      };
  BH_Multisize_HouseAds?:
    | T
    | {
        active?: T;
        imageUrl?: T;
        link?: T;
        code?: T;
        sizePreset?: T;
        customWidth?: T;
        customHeight?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  sliders?:
    | T
    | {
        title?: T;
        category?: T;
        slug?: T;
        image?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}